name: Validate API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install spectral-cli openapi-spec-validator swagger-cli
    
    - name: Validate OpenAPI spec with Spectral
      run: |
        spectral lint specs/openapi.yaml
    
    - name: Validate OpenAPI spec with openapi-spec-validator
      run: |
        openapi-spec-validator specs/openapi.yaml
    
    - name: Validate with Swagger CLI
      run: |
        swagger-cli validate specs/openapi.yaml
