name: Validate OpenAPI Specification

on:
  push:
    branches: [ main ]
    paths:
      - 'specs/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'specs/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: specs/openapi.yaml

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Spectral
        run: npm install -g @stoplight/spectral-cli

      - name: Lint OpenAPI with Spectral
        run: spectral lint specs/openapi.yaml
